Add  .telepaste in telegraph.py to paste text content into telegraph
UsergeTeam/Userge pull request #298
Opened 2021-04-09 06:28 UTC by Jigarvarma2005

2021-04-09 06:28 UTC, pep8speaks commented
@Jigarvarma2005, Thanks for opening this PR.

* In the file [`userge/plugins/utils/telegraph.py`](https://github.com/UsergeTeam/Userge/blob/6a2eac439c463d508fcc2db94ee398e53dd67a7e/userge/plugins/utils/telegraph.py):

> [Line 63:1](https://github.com/UsergeTeam/Userge/blob/6a2eac439c463d508fcc2db94ee398e53dd67a7e/userge/plugins/utils/telegraph.py#L63): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 63:36](https://github.com/UsergeTeam/Userge/blob/6a2eac439c463d508fcc2db94ee398e53dd67a7e/userge/plugins/utils/telegraph.py#L63): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 63:101](https://github.com/UsergeTeam/Userge/blob/6a2eac439c463d508fcc2db94ee398e53dd67a7e/userge/plugins/utils/telegraph.py#L63): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (230 > 100 characters)
> [Line 68:8](https://github.com/UsergeTeam/Userge/blob/6a2eac439c463d508fcc2db94ee398e53dd67a7e/userge/plugins/utils/telegraph.py#L68): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 73:30](https://github.com/UsergeTeam/Userge/blob/6a2eac439c463d508fcc2db94ee398e53dd67a7e/userge/plugins/utils/telegraph.py#L73): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2021-04-09 06:54 UTC, Krishna-Singhal commented
@Jigarvarma2005 , can you add that method in single command

2021-04-09 07:46 UTC, Jigarvarma2005 commented
> @Jigarvarma2005 , can you add that method in single command

Ok lemme try

2021-04-09 09:06 UTC, Jigarvarma2005 reviewed
all fixed

2021-04-09 09:12 UTC, Krishna-Singhal requested changes

2021-04-09 09:12 UTC, Krishna-Singhal commented on userge/plugins/utils/telegraph.py
> +        await message.edit(f"**Your text pasted to [telegraph]({t_url})**", disable_web_page_preview=True)
break this line and give indents

2021-04-09 09:20 UTC, Krishna-Singhal requested changes

2021-04-09 09:20 UTC, Krishna-Singhal commented on userge/plugins/utils/telegraph.py
> +    'examples': " reply {tr}telegraph to `This is header|This is my content`\n (You can use html code)"})
this line also

2021-04-09 09:20 UTC, Krishna-Singhal commented on userge/plugins/utils/telegraph.py
> +            content = content.split("|")
add maxsplit=1 in split()

2021-04-09 09:20 UTC, Krishna-Singhal commented on userge/plugins/utils/telegraph.py
> +            if len(content) == 2:
I think no need of if else here,

just write 

`if '|' in replied.text:`
`....content = text.split('|', maxsplit=1)`
`....header = content[0]`
`....text = content[1]`

2021-04-10 06:14 UTC, rking32 commented
Hi @Jigarvarma2005, thanks for this pr

2021-04-10 06:15 UTC, merged