Add support to eval from .py and .txt file😋
UsergeTeam/Userge pull request #313
Opened 2021-04-26 15:22 UTC by Jigarvarma2005

When in telegram we paste code most of times the syntax changes and we need to correct them there, so this

2021-04-26 15:22 UTC, pep8speaks commented
@Jigarvarma2005, Thanks for opening this PR.

* In the file [`userge/plugins/tools/executor.py`](https://github.com/UsergeTeam/Userge/blob/2f0e2f5f8a18e0b3f6f70f579dab042d66a0e94f/userge/plugins/tools/executor.py):

> [Line 167:9](https://github.com/UsergeTeam/Userge/blob/2f0e2f5f8a18e0b3f6f70f579dab042d66a0e94f/userge/plugins/tools/executor.py#L167): [E129](https://duckduckgo.com/?q=pep8%20E129) visually indented line with same indent as next logical line
> [Line 169:17](https://github.com/UsergeTeam/Userge/blob/2f0e2f5f8a18e0b3f6f70f579dab042d66a0e94f/userge/plugins/tools/executor.py#L169): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 173:13](https://github.com/UsergeTeam/Userge/blob/2f0e2f5f8a18e0b3f6f70f579dab042d66a0e94f/userge/plugins/tools/executor.py#L173): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent

2021-04-26 15:32 UTC, Krishna-Singhal commented
@Jigarvarma2005 try this 

https://del.dog/irferfizur

2021-04-26 15:33 UTC, Jigarvarma2005 commented
> @Jigarvarma2005, Thanks for updating this PR.
> 
> * In the file [`userge/plugins/tools/executor.py`](https://github.com/UsergeTeam/Userge/blob/68c434ba992c31775b39c66118c6526dd4465aa2/userge/plugins/tools/executor.py):
> 
> > [Line 167:16](https://github.com/UsergeTeam/Userge/blob/68c434ba992c31775b39c66118c6526dd4465aa2/userge/plugins/tools/executor.py#L167): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> > [Line 169:14](https://github.com/UsergeTeam/Userge/blob/68c434ba992c31775b39c66118c6526dd4465aa2/userge/plugins/tools/executor.py#L169): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> 
> ##### Comment last updated at 2021-04-26 15:29:30 UTC

Why😬😬

2021-04-26 15:43 UTC, Jigarvarma2005 commented
> @Jigarvarma2005, Thanks for updating this PR.
> 
> * In the file [`userge/plugins/tools/executor.py`](https://github.com/UsergeTeam/Userge/blob/55ff25fa689e982420e1077f2d4d53ac4e0d3b7d/userge/plugins/tools/executor.py):
> 
> > [Line 170:5](https://github.com/UsergeTeam/Userge/blob/55ff25fa689e982420e1077f2d4d53ac4e0d3b7d/userge/plugins/tools/executor.py#L170): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> 
> ##### Comment last updated at 2021-04-26 15:42:19 UTC

Why pep8 always suck🤨

2021-04-27 07:22 UTC, Phyco-Ninja commented
🐛 🐛 🐛

2021-04-27 10:55 UTC, Phyco-Ninja commented on userge/plugins/tools/executor.py
> +    if (rep.document and rep.document.file_name.endswith('.txt', '.py')
this statement will give:
* AttributeError if reply_to_message is None
* TypeError for endswith

```python
    if (
        rep and rep.document  and rep.document.file_name.endswith(('.txt', '.py'))
        and rep.document.file_size <= 2097152
    ):
        ...
```

2021-04-27 11:00 UTC, Jigarvarma2005 commented on userge/plugins/tools/executor.py
> +    if (rep.document and rep.document.file_name.endswith('.txt', '.py')
oof i forgot

2021-04-29 08:13 UTC, Jigarvarma2005 commented
> @Jigarvarma2005, Thanks for updating this PR.
> 
> There are currently no PEP 8 issues detected in this Pull Request. Cheers! 🍻
> 
> ##### Comment last updated at 2021-04-29 08:12:16 UTC

😌
🤗

2021-04-29 08:25 UTC, Jigarvarma2005 reviewed
Now done

2021-05-01 12:25 UTC, rking32 commented
good, but dangerous

2021-05-01 12:42 UTC, Jigarvarma2005 commented
> good, but dangerous

Why?😬🤔

2021-05-02 12:17 UTC, rking32 commented
files may contain dangerous codes like `delete_account, spam, ...`. if anyone `.eval` that, boom ...

2021-05-02 12:22 UTC, Jigarvarma2005 commented
> files may contain dangerous codes like `delete_account, spam, ...`. if anyone `.eval` that, boom ...

😬🤨😑

2021-05-02 12:25 UTC, Jigarvarma2005 commented
> files may contain dangerous codes like `delete_account, spam, ...`. if anyone `.eval` that, boom ...

Close this PR🤗

2021-05-02 13:54 UTC, rking32 commented
@Jigarvarma2005 lets wait for others opinions.

2021-05-02 14:09 UTC, Jigarvarma2005 commented
> @Jigarvarma2005 lets wait for others opinions.

OK

2021-06-05 06:54 UTC, Harsh-br0 commented on userge/plugins/tools/executor.py
> +        if cmd_flag and cmd_flag == "-s":
Sup @Jigarvarma2005 
It may not work if user replies to file and input_str have flag + extra stuff which is mistakenly typed
So mention the flag explicitly can avoid this issue
``` suggestion
        if cmd_flag:
```
And `cmd_flag` can be like
``` python
cmd_flag = "-s" in message.flags
```

2021-06-06 04:14 UTC, Jigarvarma2005 commented on userge/plugins/tools/executor.py
> +        if cmd_flag and cmd_flag == "-s":
> Sup @Jigarvarma2005
> It may not work if user replies to file and input_str have flag + extra stuff which is mistakenly typed
> So mention the flag explicitly can avoid this issue
> 
> And `cmd_flag` can be like
> 
> ```python
> cmd_flag = "-s" in message.flags
> ```

Thanks for suggetion

2021-06-06 07:03 UTC, Krishna-Singhal requested changes

2021-06-06 07:03 UTC, Krishna-Singhal commented on userge/plugins/tools/executor.py
> +        if "-s" in cmd_flag:
`cmd_flag = message.input_str or message.flags`

`if cmd_flag and "-s" in cmd_flag:`
`....silent_mode = True`

2021-06-06 15:15 UTC, Krishna-Singhal commented
seems good now.

2021-08-28 17:37 UTC, pseudokawaii commented
> 
> 
> > @Jigarvarma2005, Thanks for updating this PR.
> > 
> > * In the file [`userge/plugins/tools/executor.py`](https://github.com/UsergeTeam/Userge/blob/55ff25fa689e982420e1077f2d4d53ac4e0d3b7d/userge/plugins/tools/executor.py):
> > 
> > > [Line 170:5](https://github.com/UsergeTeam/Userge/blob/55ff25fa689e982420e1077f2d4d53ac4e0d3b7d/userge/plugins/tools/executor.py#L170): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> > 
> > 
> > ##### Comment last updated at 2021-04-26 15:42:19 UTC
> 
> Why pep8 always suck🤨

Devs should just remove style checks from Deepsource issue config. It's useless and annoying. Using a transformer like `autopep8`  is rather smarter choice if style really matters.

2021-08-29 05:59 UTC, rking32 commented
> > > @Jigarvarma2005, Thanks for updating this PR.
> > > 
> > > * In the file [`userge/plugins/tools/executor.py`](https://github.com/UsergeTeam/Userge/blob/55ff25fa689e982420e1077f2d4d53ac4e0d3b7d/userge/plugins/tools/executor.py):
> > > 
> > > > [Line 170:5](https://github.com/UsergeTeam/Userge/blob/55ff25fa689e982420e1077f2d4d53ac4e0d3b7d/userge/plugins/tools/executor.py#L170): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> > > 
> > > 
> > > ##### Comment last updated at 2021-04-26 15:42:19 UTC
> > 
> > 
> > Why pep8 always suckraised_eyebrow
> 
> Devs should just remove style checks from Deepsource issue config. It's useless and annoying. Using a transformer like `autopep8` is rather smarter choice if style really matters.

its cool somehow (deepsource) :D

2021-08-29 06:31 UTC, pseudokawaii commented
@rking32 auto transformers are way cooler ~
https://deepsource.io/docs/transformer/autopep8

2021-09-07 14:24 UTC, fayasnoushad approved these changes

2021-12-21 10:36 UTC, Harsh-br0 commented
> This is a massive security loophole, and we don't need to be giving users an extra way to shoot themselves in the foot. I vote this be immediately closed and not merged.

Bruh

2022-01-04 16:05 UTC, tomyprs commented
🤨

2022-01-08 08:15 UTC, Jigarvarma2005 commented
Will open it again, if need🤔

2022-01-08 08:15 UTC, closed without merging

2022-03-07 18:07 UTC, Jigarvarma2005 commented
Needed🥲