improve gadmin tools
UsergeTeam/Userge pull request #415
Opened 2021-12-08 18:44 UTC by subinps

Allow userge to ban channels in groups.
Option to restrict members chatting as channel.

2021-12-08 18:44 UTC, pep8speaks commented
@subinps, Thanks for opening this PR.

* In the file [`userge/plugins/admin/gadmin.py`](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py):

> [Line 26:13](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L26): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 27:18](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L27): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 29:1](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L29): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 163:23](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L163): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 221:23](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L221): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 637:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L637): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 100 characters)
> [Line 641:9](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L641): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 644:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L644): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 100 characters)
> [Line 658:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L658): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 100 characters)
> [Line 661:91](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L661): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 661:93](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L661): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 665:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L665): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 100 characters)
> [Line 674:44](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L674): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 679:43](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L679): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 679:58](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L679): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 679:76](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L679): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 679:92](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L679): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 679:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L679): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 100 characters)
> [Line 682:74](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L682): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 685:74](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L685): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 687:47](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L687): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 692:1](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L692): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 694:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L694): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 100 characters)
> [Line 695:5](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L695): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 708:9](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L708): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 716:35](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L716): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 717:28](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L717): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 719:80](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L719): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 719:82](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L719): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 722:40](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L722): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 723:39](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L723): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 723:54](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L723): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 723:71](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L723): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 723:88](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L723): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 730:1](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L730): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 732:101](https://github.com/UsergeTeam/Userge/blob/cefd1679da7d3ac0a3d76e1f6bc662ebbdfdb0bc/userge/plugins/admin/gadmin.py#L732) [...]

2021-12-08 23:45 UTC, Jigarvarma2005 commented
tested before adding??

2021-12-09 07:37 UTC, Krishna-Singhal requested changes

2021-12-09 07:37 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        if not await DB.find_one({'chat_id':chat_id}):
add `message.edit` to notify user that chat is enabled

2021-12-09 07:37 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +    'description': "Restrict the users from chatting in group as ther channels.\nUse appropriate flags to toggle between ban and delete_only.",
here is typo, `ther` -> `their`

2021-12-09 07:37 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
merge both if else statements with

`await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}}, upsert=True)`

2021-12-09 07:37 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        return await message.edit('No input given', del_in=5)
use `message.err` here

2021-12-09 07:37 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
merge both if else statements with

`await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}}, upsert=True)`

2021-12-09 07:37 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +            await CHANNEL.log(
add a Log message for chat where user has kicked and delete it in 10 seconds.

2021-12-09 07:44 UTC, subinps commented on userge/plugins/admin/gadmin.py
> +        elif message.input_str:
https://github.com/UsergeTeam/Userge/blob/alpha/userge/core/types/bound/message.py#L141 , here it return None since if a channel id is passed it will be negative number.

2021-12-09 07:53 UTC, subinps commented on userge/plugins/admin/gadmin.py
> +        if not await DB.find_one({'chat_id':chat_id}):
Notifying [here](https://github.com/UsergeTeam/Userge/blob/c3e426ba9e62d206da9478833a4d0ee85b62c0d6/userge/plugins/admin/gadmin.py#L694) and [here](https://github.com/UsergeTeam/Userge/blob/c3e426ba9e62d206da9478833a4d0ee85b62c0d6/userge/plugins/admin/gadmin.py#L697)

2021-12-09 08:16 UTC, subinps commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
Even if i use upsert, to pass a default value for `"ban" `and `"enabled"`, i should check the db using the same find_one right?
 if i use `await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}}, upsert=True)` ,  [here](https://github.com/UsergeTeam/Userge/blob/c3e426ba9e62d206da9478833a4d0ee85b62c0d6/userge/plugins/admin/gadmin.py#L37) it will raise a `KeyError` since `"ban"` and `"enabled"` will be empty if upserted.

2021-12-09 10:39 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        elif message.input_str:
> https://github.com/UsergeTeam/Userge/blob/alpha/userge/core/types/bound/message.py#L141 , here it return None since if a channel id is passed it will be negative number.

hmmm

2021-12-09 10:52 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
no i guess, i didnt used other vars to upsert.

merge both with 

```python
await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed, 'ban': False, 'enabled': False}}, upsert=True)
```

2021-12-09 10:55 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
replace all `insert_one` with `update_one` with `upsert=True` and pass all values in it.

2021-12-09 11:03 UTC, Krishna-Singhal commented
you should update ban and kick command so that those commands can also ban users messaging in chat as channel.

2021-12-09 11:05 UTC, subinps commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
Sorry, i did't get that.

CASE 1:
Suppose if a document already exist in db.
lets say `{"chat_id": -1000000000, "ban": True, "enabled": True, allowed:[-10025252522]}`
Now if i want to add one channel  ( -10025222525 ) to allowed list, if i use 
`await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed, 'ban': False, 'enabled': False}}, upsert=True)`
after the update it will be like this 
 `{"chat_id": -1000000000, "ban": False, "enabled": False, allowed:[-10025252522,  -10025222525]}`
 
 I mean the existing settings will be reverted to default.
 
 CASE 2:
 No document exist in db
 in this case the it will work as expected.
 
 Excuse me if am wrong 😬.

2021-12-09 11:13 UTC, subinps commented
> you should update ban and kick command so that those commands can also ban users messaging in chat as channel.

Ban and unban is updated, it wont make sense to kick a channel, since even if we kick the channel, still the user can continue in the chat, only change will be he wont be able to send message with his channel  for a minute. that is until the channel gets unbanned.

2021-12-10 04:54 UTC, Krishna-Singhal commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
you can check with global variables if document is already there

2021-12-10 15:53 UTC, subinps commented on userge/plugins/admin/gadmin.py
> +        await DB.update_one({'chat_id': chat_id}, {'$set': {'allowed': allowed}})
> you can check with global variables if document is already there

done, thanks.

2021-12-10 19:49 UTC, Krishna-Singhal approved these changes

2021-12-12 17:54 UTC, subinps commented
Realisations :(

2021-12-12 18:12 UTC, rking32 commented
Why did you close this? I was reviewing it. It isn't working as expected?

2021-12-12 18:13 UTC, subinps commented
> Why did you close this? I was reviewing it. It isn't working as expected?

No, just realised that this will be useless :)

2021-12-12 18:17 UTC, rking32 commented
But many users have requested and have been waiting for this feature. So, I don't think that this would be useless.

2021-12-12 18:35 UTC, subinps commented
> But many users have requested and have been waiting for this feature. So, I don't think that this would be useless.

I believe somebody else can do this in a better way 😅.

2021-12-13 06:55 UTC, rking32 commented
But we can try to improve this without making a new one from scratch.

2021-12-13 07:03 UTC, rking32 commented
if you agree, you can reopen this PR

2021-12-13 13:45 UTC, NavaneethRenjith8282 commented
> Allow userge to ban channels in groups. Option to restrict members chatting as channel.

Hello @subinps,
You didn't want to close this issue.
I'm telling about this because, they've discussed about this pull request in **[Userge OffTopic](https://t.me/UsergeSpam)** group and gave an opinion: “It want to be merged 🥲” **[View message...](https://t.me/UserGeSpam/338678)**
So, can you please reopen this pull request?

2021-12-13 14:15 UTC, subinps commented
> if you agree, you can reopen this PR

[Telegram introduced such feature meant to be used by others , and it makes no sense  that we restrict them from that being used.](https://t.me/keralagram/1402760)

I thought , you may be in that opinion since there was no response for the PR for more than 4 days and so decided that better to close from my side 😬. 

If it's okay I'm ready to reopen :(

2021-12-13 15:45 UTC, Jigarvarma2005 commented
> > if you agree, you can reopen this PR
> 
> [Telegram introduced such feature meant to be used by others , and it makes no sense that we restrict them from that being used.](https://t.me/keralagram/1402760)
> 
> I thought , you may be in that opinion since there was no response for the PR for more than 4 days and so decided that better to close from my side 😬.
> 
> If it's okay I'm ready to reopen :(

usefull for admims

2021-12-14 13:08 UTC, StillAliveTG commented
Please reopen😔

2021-12-14 13:30 UTC, NavaneethRenjith8282 commented on userge/plugins/admin/gadmin.py
> +        return await message.edit('No input given', del_in=5)
> use `message.err` here

And, delete `del_in` part, because error messages (`message.err`) can't be deleted.

2021-12-14 13:31 UTC, NavaneethRenjith8282 commented on userge/plugins/admin/gadmin.py
> +    'description': "Restrict the users from chatting in group as ther channels.\nUse appropriate flags to toggle between ban and delete_only.",
And, @subinps also gets this typos many times. I seen that he made some typos in his repos also 😂

2021-12-15 14:58 UTC, Krishna-Singhal requested changes

2021-12-15 17:46 UTC, Krishna-Singhal approved these changes

2021-12-16 04:53 UTC, rking32 commented
Mainly improved the logic of `ban` and `unban` + `else` part of `no_channels` + refactored `allow_channel` and `disallow_channel`. Did i break anything? :)

I'm going to test the whole thing...

2021-12-16 05:41 UTC, Krishna-Singhal approved these changes

2021-12-16 05:57 UTC, rking32 commented
@Krishna-Singhal thanks for your time :)

2021-12-16 06:32 UTC, Krishna-Singhal commented
> @Krishna-Singhal thanks for your time :)

My pleasure 😄

2021-12-16 06:50 UTC, rking32 commented
@subinps Thank you so much for this awesome feature and also thanks @Krishna-Singhal for helping us to finish this thing as fast as possible :)

2021-12-16 06:52 UTC, merged

2021-12-17 16:07 UTC, NavaneethRenjith8282 commented
> tested before before making pr?? , when pyrogram added ability to ban channels? 🧐

@Jigarvarma2005 it has been added in [Telegram Bot API](https://core.telegram.org/bots/api) also.

2021-12-17 16:10 UTC, NavaneethRenjith8282 commented on userge/plugins/admin/gadmin.py
> +        return await message.edit('No input given', del_in=5)
> > > use `message.err` here
> > 
> > 
> > And, delete `del_in` part, because error messages (`message.err`) can't be deleted.
> 
> Are you sure ?

Yes, @Krishna-Singhal.
Because, **Userge** doesn't have `del_in` in **ERROR** message (`message.err`).

2021-12-17 16:13 UTC, NavaneethRenjith8282 commented on userge/plugins/admin/gadmin.py
> +            await CHANNEL.log(
> add a Log message for chat where user has kicked and delete it in 10 seconds.

**Why?**

2021-12-22 10:39 UTC, NavaneethRenjith8282 commented on userge/plugins/admin/gadmin.py
> +        '-d': "Disable restriction"},
Why did you added `-d` flag to disable restriction? 
@subinps, add feature to use `no_channels` command again for disabling restriction, instead of using `-d` flag.