Updated details and text of all plugins
UsergeTeam/Userge pull request #417
Opened 2021-12-11 14:26 UTC by NavaneethRenjith8282

I've given some changes to details and texts of all plugins in Userge. I've taken 3-4 hours to make this change.
## Explanation of some changes
I've changed smiley icons to emojis.
_For example, I've changed : ) icon to 🙂 emoji._
Then, I've made changes to some texts.
### Changes in voice-call plugin
I've given a change to `voice-call` plugin.
I've changed it's name to `video-chat`.
Because, Telegram has changed the name of Voice Chat as `Video Chat`.
## I'm hoping...
I'm hoping that you'll push this because, I've worked for 3-4 hours for this change.

2021-12-11 14:26 UTC, pep8speaks commented
@NavaneethRenjith8282, Thanks for opening this PR.





* In the file [`userge/plugins/admin/gadmin.py`](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/admin/gadmin.py):

> [Line 386:101](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/admin/gadmin.py#L386): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 100 characters)











































* In the file [`userge/plugins/utils/botpm.py`](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/botpm.py):

> [Line 77:20](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/botpm.py#L77): [E999](https://duckduckgo.com/?q=pep8%20E999) SyntaxError: invalid syntax
> [Line 77:21](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/botpm.py#L77): [E211](https://duckduckgo.com/?q=pep8%20E211) whitespace before '('

















* In the file [`userge/plugins/utils/pmpermit.py`](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/pmpermit.py):

> [Line 158:56](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/pmpermit.py#L158): [E999](https://duckduckgo.com/?q=pep8%20E999) SyntaxError: EOL while scanning string literal
> [Line 159:24](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/pmpermit.py#L159): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent
> [Line 161:1](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/pmpermit.py#L161): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent
> [Line 161:35](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/pmpermit.py#L161): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 161:45](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/pmpermit.py#L161): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator











* In the file [`userge/plugins/utils/weather.py`](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/weather.py):

> [Line 46:15](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/weather.py#L46): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'msg'
> [Line 47:75](https://github.com/UsergeTeam/Userge/blob/5ca5cf13a28c60e43876c968644014ff3675e2e5/userge/plugins/utils/weather.py#L47): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2021-12-11 15:17 UTC, Krishna-Singhal requested changes

2021-12-11 15:17 UTC, Krishna-Singhal commented on userge/plugins/tools/ping.py
> +    await message.edit(f"**Pong! I'm alive!**\n`{m_s} ms`")
atleast dont change ping 😢😫

2021-12-11 15:38 UTC, NavaneethRenjith8282 commented on userge/plugins/tools/ping.py
> +    await message.edit(f"**Pong! I'm alive!**\n`{m_s} ms`")
Ok, ok, ok.

2021-12-11 15:38 UTC, NavaneethRenjith8282 commented on userge/plugins/tools/ping.py
> +    await message.edit(f"**Pong! I'm alive!**\n`{m_s} ms`")
> atleast dont change ping 😢😫

Ok, ok, ok.
I've changed it to defaults.

2021-12-11 15:42 UTC, NavaneethRenjith8282 commented on userge/plugins/tools/ping.py
> +    await message.edit(f"**Pong! I'm alive!**\n`{m_s} ms`")
> atleast dont change ping 😢😫

Really, I've changed it as like `ping` in [Ultroid](https://github.com/TeamUltroid/Ultroid).
If it doesn't matter to be want, don't be worried. I've changed it.

2021-12-12 06:52 UTC, NavaneethRenjith8282 commented
> @NavaneethRenjith8282, Thanks for updating this PR.
> 
> * In the file [`userge/plugins/utils/weather.py`](https://github.com/UsergeTeam/Userge/blob/0c6f91ac2d972a25def59a1c0184ce3bdda4bfcb/userge/plugins/utils/weather.py):
> 
> > [Line 47:76](https://github.com/UsergeTeam/Userge/blob/0c6f91ac2d972a25def59a1c0184ce3bdda4bfcb/userge/plugins/utils/weather.py#L47): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> 
> ##### Comment last updated at 2021-12-12 06:49:23 UTC

Lint Errors fixed due to recommendation of @Krishna-Singhal . [View message here...](https://t.me/usergeot/777691)

2021-12-13 10:54 UTC, Krishna-Singhal commented
> > @NavaneethRenjith8282, Thanks for updating this PR.
> > 
> > * In the file [`userge/plugins/utils/weather.py`](https://github.com/UsergeTeam/Userge/blob/0c6f91ac2d972a25def59a1c0184ce3bdda4bfcb/userge/plugins/utils/weather.py):
> > 
> > > [Line 47:76](https://github.com/UsergeTeam/Userge/blob/0c6f91ac2d972a25def59a1c0184ce3bdda4bfcb/userge/plugins/utils/weather.py#L47): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> > 
> > 
> > ##### Comment last updated at 2021-12-12 06:49:23 UTC
> 
> Lint Errors fixed due to recommendation of @Krishna-Singhal . [View message here...](https://t.me/usergeot/777691)

They are still there :(

2021-12-13 13:54 UTC, NavaneethRenjith8282 commented
> > Lint Errors fixed due to recommendation of @Krishna-Singhal . [View message here...](https://t.me/usergeot/777691)
> 
> They are still there :(

No problem, @Krishna-Singhal. You can still edit this because, I've given it's access “Allow edit access by maintainers”. So, you can edit it and merge it. 🙂

2021-12-13 15:37 UTC, Jigarvarma2005 commented
> I've given some changes to details and texts of all plugins in Userge. I've taken 3-4 hours to make this change.
> 
> ## Explanation of some changes
> I've changed smiley icons to emojis. Because, messages in Telegram supports emojis, as in inline also. _For example, I've changed_ :) _icon to_ 🙂 _emoji._ Then, I've made changes to some texts.
> 
> ## Renamed some plugins...
> * I've given a change to `voice-call` plugin.
>   I've changed it's name to `video-chat`.
>   Because, Telegram has changed renamed Voice Chat as **Video Chat**.
> * I've changed `gdrive` to `google_drive`. Because, Google Drive, Google are trademarks of **Google LLC**. And, I don't like to show it as `GDrive`. That's why I made up this change.
> 
> And, there is another changes also. You can check it at the [Commits](https://github.com/UsergeTeam/Userge/pull/417/commits) tab.
> 
> ## I'm hoping...
> I'm hoping that you'll push this because, I've worked for 3-4 hours for this change.
> 
> ### Note:
> * I've changed only the names and texts of plugins, commands, and it's texts. I didn't changed any other thing.

Try this for weather.py pep8 fix
👇👇
[Weather.py](https://katb.in/enudulerobo.py)

2021-12-14 11:47 UTC, NavaneethRenjith8282 commented
> Try this for weather.py pep8 fix 👇👇 [Weather.py](https://katb.in/enudulerobo.py)

**Thanks for helping me,** @Jigarvarma2005! I've **changed** the [commit](https://github.com/UsergeTeam/Userge/pull/417/commits/fae3cc5b8a0ec9163f7fd006a4737c44dd03bcc5) to the text you've given.

2021-12-14 11:49 UTC, Jigarvarma2005 commented
> > Try this for weather.py pep8 fix 👇👇 [Weather.py](https://katb.in/enudulerobo.py)
> 
> **Thanks for helping me,** @Jigarvarma2005! I've **changed** the [commit](https://github.com/UsergeTeam/Userge/pull/417/commits/fae3cc5b8a0ec9163f7fd006a4737c44dd03bcc5) to the text you've given.

fix deepsource too

2021-12-14 12:36 UTC, NavaneethRenjith8282 commented
> > > Try this for weather.py pep8 fix 👇👇 [Weather.py](https://katb.in/enudulerobo.py)
> > 
> > 
> > **Thanks for helping me,** @Jigarvarma2005! I've **changed** the [commit](https://github.com/UsergeTeam/Userge/pull/417/commits/fae3cc5b8a0ec9163f7fd006a4737c44dd03bcc5) to the text you've given.
> 
> fix deepsource too

I want to consider creating decoration with `@staticmethod` because, [DeepSource](https://deepsource.io/gh/UsergeTeam/Userge/) says to do it for perfomance improvements. 
Should I want to do [this](https://deepsource.io/gh/UsergeTeam/Userge/run/f9af76d6-0144-439a-9394-18ac613ae2f6/python/)?

2021-12-14 13:02 UTC, Jigarvarma2005 commented
> > > > Try this for weather.py pep8 fix 👇👇 [Weather.py](https://katb.in/enudulerobo.py)
> > > 
> > > 
> > > **Thanks for helping me,** @Jigarvarma2005! I've **changed** the [commit](https://github.com/UsergeTeam/Userge/pull/417/commits/fae3cc5b8a0ec9163f7fd006a4737c44dd03bcc5) to the text you've given.
> > 
> > 
> > fix deepsource too
> 
> I want to consider creating decoration with `@staticmethod` because, [DeepSource](https://deepsource.io/gh/UsergeTeam/Userge/) says to do it for perfomance improvements. 😕 It wants to be in this line:
> 
> ```
>   async def paste(self, ses: aiohttp.ClientSession,
> ```
> 
> Should I want to do [this](https://deepsource.io/gh/UsergeTeam/Userge/run/f9af76d6-0144-439a-9394-18ac613ae2f6/python/)?

try this for deepsource

[rss_feed.py](https://katb.in/egileqoyofi)

2021-12-14 13:08 UTC, Jigarvarma2005 commented
lol

2021-12-14 13:10 UTC, Harsh-br0 commented
He can just practice GitHub with this PR ig , already messed with code

2021-12-14 13:23 UTC, Jigarvarma2005 commented
> He can just practice GitHub with this PR ig , already messed with code

yeah

2021-12-14 13:27 UTC, NavaneethRenjith8282 commented
# Sorry...
I don't know why this issue need this much problems. Someone says in comment:

>> @Harsh-br0 :
>
> He can just practice GitHub with this PR ig , already messed with code

Yes. I can also do it.
But, there is still many problems in this pull request. So, maybe I think to **close this pull request**.
Don't worry, I won't close this now.
**Please wait until I get any ideas...**

2021-12-14 13:33 UTC, Harsh-br0 commented
> I don't know why this issue need this much problems

Not your fault too but you should control your curiosity like first get the knowledge before doing it and be eligible to go for it

2021-12-15 04:59 UTC, rking32 commented
@NavaneethRenjith8282 Sorry to say this. Apparently, you have messed up the code.

2021-12-17 11:17 UTC, NavaneethRenjith8282 commented
> @NavaneethRenjith8282 Sorry to say this. Apparently, you have messed up the code.
Sorry everyone. I'm closing now.

2021-12-17 11:19 UTC, NavaneethRenjith8282 commented
> # Sorry...
> I don't know why this issue need this much problems. Someone says in comment:
> 
> > > @Harsh-br0 :
> > 
> > 
> > He can just practice GitHub with this PR ig , already messed with code
> 
> Yes. I can also do it. But, there is still many problems in this pull request. So, maybe I think to **close this pull request**. Don't worry, I won't close this now. **Please wait until I get any ideas...**

So, **closing** this issue now.
**Thanks for helping me!!!*** ❤️❤️❤️

2021-12-17 11:19 UTC, closed without merging